baseurl = "https://jsta.rbind.io/"
languageCode = "en-us"
title = "Joseph Stachelek"
theme = "hugo-lithium-theme"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
enableEmoji = true
footnotereturnlinkcontents = "↩"
rssLimit = 30

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "CV"
    url = "/cv/"
[[menu.main]]
    name = "Blog"
    url = "/blog/"
[[menu.main]]
    name = "Extras"
    url = "/extras/"

[params]
    description = "Personal website of Joseph Stachelek"
    dateFormat = "2006/01/02"
    customCSS = ["css/custom.css"]
    customJS = ["js/center-img.js", "js/right-quote.js", "js/no-highlight.js", "js/fix-footnote.js"]

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml", "tex"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo link to homepage"
    
    [params.social]
    twitter = "__jsta"
    github = "jsta"
    