baseurl = "https://jsta.rbind.io/"
languageCode = "en-us"
title = "J Stachelek"
theme = "hugo-lithium-theme"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
enableEmoji = true
footnotereturnlinkcontents = "↩"
rssLimit = 30

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
[[menu.main]]
    name = "Products"
    url = "/products/"
    weight = 2
[[menu.main]]
    name = "CV"
    url = "/cv/"
    weight = 3
[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 4
[[menu.main]]
    name = "Extras"
    url = "/extras/"
    weight = 5

[params]
    description = "Personal website of Joseph Stachelek"
    dateFormat = "2006/01/02"
    customCSS = ["css/style-new.css", "css/custom.css"]
    customJS = ["js/center-img.js", "js/right-quote.js", "js/no-highlight.js", "js/fix-footnote.js"]

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml", "tex"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Homepage link"
    
    [params.social]
    twitter = "__jsta"
    github = "jsta"
    