---
title: ""
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    self_contained: FALSE
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(DT)
library(widgetframe)
```


```{r, echo=FALSE, out.width="100%", warning=FALSE}
read_latest <- function(){
  fpath <- "../static/data/"
  if(!file.exists(fpath)){
    fpath <- "static/data/"
  }
  
  archives <- list.files(fpath, pattern = "*likes.rds", 
                         full.names = TRUE, include.dirs = TRUE)
  dates <- sapply(archives, 
               function(x) strsplit(x, "_")[[1]][1])
  dates <- as.Date(
    sapply(dates, function(x) substring(x, nchar(x)-9, nchar(x))))
    
  dt <- readRDS(archives[which.max(dates)])
  dt <- data.frame(dt)
}

dt <- read_latest()
good_cols <- as.numeric(apply(dt, 2, function(x) sum(is.na(x)) / nrow(dt))) < 0.2
dt <- dt[,good_cols]

dt <- dplyr::select(dt, -user_id, -lang, -is_retweet, -status_id, -urls_url, -urls_t.co, -geo_coords, -coords_coords, -source, -bbox_coords, -favorite_count,
                    -retweet_count)
dt$created_at <- strptime(as.POSIXct(dt$created_at), format = "%Y-%m-%d")

createLink <- function(x) {
  sprintf(paste0('<a href="', URLdecode(x),'" target="_blank">', substr(x, 1, 25) ,'</a>'))
}

dt$urls_expanded_url <- lapply(dt$urls_expanded_url, function(x) sapply(x, createLink))

dt_table <- DT::datatable(dt, 
                          options = list(# dom = 't',
                                         scrollX = TRUE,
                                         autoWidth = TRUE,
                  columnDefs = list(#list(width = '5%', targets = c(0,1,3)), 
                                    list(width = '70%', targets = c(2)))), 
                          rownames = FALSE,
                          fillContainer = TRUE,
                      width = "100%", 
                  colnames = c("Date", "Handle", "Text", "URL"))
dt_table <- formatDate(dt_table, columns = c(1))
dt_table <- formatStyle(dt_table, columns = 1:4, fontSize = '70%')
dt_table <- formatStyle(dt_table, columns = 3, width = '500px')
frameWidget(dt_table, width = "100%", height = 900, options = frameOptions(allowfullscreen = TRUE))

```
